import Footer from '@/components/widgets/footer/Footer'
import Header from '@/components/widgets/header/Header'
import Providers from '@/providers/Providers'
import type { Metadata } from 'next'
import { Libre_Franklin } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const libre = Libre_Franklin({ subsets: ['cyrillic', 'latin'] })

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={libre.className}>
				<Providers>
					<Header />
					{children}
					<Footer />
				</Providers>
			</body>
		</html>
	)
}
